function [byu] = BYU()
%
% Creates a new empty tileset object.
%
byu = struct( ...
	'nParts', 1, ...
	'nVertices', 0, ...
	'nPolygons', 0, ...
	'nConnectors', 0, ...
    'adjacency', zeros([0,3]), ...
	'polyList', [1 0], ...
	'filenames', {''}, ...
	'vertices', {zeros([0 3])}, ...
	'neighbors', [], ...
	'inPolygons', [] );
byu	= class(byu, 'BYU');
